export const WS_CONNECTION_START = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS'; 
export const WS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';
export const WS_GET_ORDERS = 'WS_GET_ORDERS';
export const WS_SEND_ORDER = 'WS_SEND_ORDER';


export const WS_CONNECTION_PROFILE_START = 'WS_CONNECTION_PROFILE_START';
export const WS_CONNECTION_PROFILE_SUCCESS = 'WS_CONNECTION_PROFILE_SUCCESS'; 
export const WS_CONNECTION_PROFILE_ERROR = 'WS_CONNECTION_PROFILE_ERROR';
export const WS_CONNECTION_PROFILE_CLOSED = 'WS_CONNECTION_PROFILE_CLOSED';
export const WS_GET_PROFILE_ORDERS = 'WS_GET_PROFILE_ORDERS';
export const WS_SEND_PROFILE_ORDER = 'WS_SEND_ORDER';